lib/rumbl_web/router.ex
defmodule RumblWeb.Router do
  use RumblWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug RumblWeb.Plugs.Auth, repo: Rumbl.Repo
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", RumblWeb do
    pipe_through :browser
    resources "/users", UserController, only: [:index, :show, :new, :create]
    resources "/sessions", SessionController, only: [:new, :create, :delete]
    resources "/watch", WatchController, only: [:show]
    get "/", PageController, :index
  end

  scope "/manage", RumblWeb do
    pipe_through [:browser, :authenticate_user]
    resources "/videos", VideoController
  end

  # Other scopes may use custom stacks.
  # scope "/api", RumblWeb do
  #   pipe_through :api
  # end
end

lib/rumbl_web/templates/page/index.html.eex
<div class="jumbotron">
  <h2>Welcome to Rumbl.io!</h2>
  <p class=​"lead"​>Check, annotate and add videos</p>
</div>

<div class="row">
  <%= for video <- @videos do %>
    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
        <%= img_tag("https://img.youtube.com/vi/#{player_id(video)}/hqdefault.jpg") %>
        <div class="caption">
          <h4><%= video.title %></h4>
          <div style="overflow: hidden; height: 65px;">
            <p><%= truncate_description(video.description) %></p>
          </div>
          <p><%= link "Watch", to: watch_path(@conn, :show, video), class: "btn btn-primary" %></p>
        </div>
      </div>
    </div>
  <% end %>
</div>